### ISSUE TITLE
Especificaciones

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/guilds.osweekends.com#1]
### Especificaciones
**Especifico**
> Vamos a hacer una web en 3 meses donde visualizar fácilmente qué herramientas/lenguaje usan, cómo avanzan y el impacto en los usuarios de los Guilds y sus proyectos. Facilitará que nuevos contributors y líderes se unan a los proyectos existentes

**Medible**
> Cuántos nuevos contributors y líderes se unen. Nuevos proyectos propuestos en OSWeekends. Nº participantes activos en los Guilds. Nº de Guilders en Slack...

**Comment by jsmanrique** [comment]
Para medir, podría ser interesante usar [GrimoireLab](https://chaoss.github.io/grimoirelab), y hasta puedo mirar cómo ayudar con los primeros pasos
