### ISSUE TITLE
¡Ayudanos!

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/guilds.osweekends.com#3]
Somos gente genial.. si te quieres unir a esta mision epica.. solo tienes que repsponder :-)

¿Quien eres?, ¿Que se te da bien? ¿Que te motiva? ¿Que te paetece hacer...?

### Que rol quieres?
*No tienes que ser una persona técnica....*

- [ ] Liderar 
- [ ] Contribuir 

### Grupos/categorias, ver #4
- [ ] Traer datos de Github
- [ ] Back
- [ ] Front
- [ ] Diseño
- [ ] Contenidos
- [ ] Haciendo cosas cool/automatizacion?

**Comment by jordibc** [comment]
Venga :)

**Comment by jyajamin** [comment]
Me uno :)

**Comment by MoniAguado** [comment]
Aúpa ahí!

**Comment by mpascualach** [comment]
Ok :)

**Comment by Alienah** [comment]
I'm in!

Me llamo Aida Albarrán y soy desarrolladora Front-End en formación (Adalab).

He usado ya en mis proyectos: grid, flexbox, SASS, Bootstrap, gulp

Me motiva trabajar en un proyecto real como éste, en colaboración con muchas personas, incluidas las que son del equipo back (que aún no he trabajado en un proyecto en colaboración con back) y aprender otras formas de organización y tecnologías que aún no conozco.

**Comment by laubolgo** [comment]
Presente!

**Comment by ismaelocaramelo** [comment]
Me too !

**Comment by DarkNPhoton** [comment]
Me apunto!!!

**Comment by carquet** [comment]
Me three !

**Comment by Tokytome** [comment]
Contad con mi espada!

**Comment by missmay4** [comment]
Holi! =)

**Comment by AnitaMartinez** [comment]
Me apunto :)

**Comment by ghost** [comment]
++

**Comment by anaisvicper** [comment]
Apuntemonos

**Comment by josealonso** [comment]
Me apunto !!

**Comment by rcascante** [comment]
Here I am!

**Comment by SebastienRetail** [comment]
por aqui tb

**Comment by anagonm** [comment]
Me uno!!

**Comment by MarColoma** [comment]
I want !!!  👯

**Comment by Xexuline** [comment]
Aquí Chechu esperando ser futuro contributor.

Actualmente desarrollador Front en con **Angular** (>2). Y haciendo algo de **Back** también con **NodeJs**, **Express**...

Por lo que podría contribuir con cualquiera de esas tecnologías.

Me gustaría aprender:
- **CSS/SCSS/SASS**.
- **Js**: Nunca se sabe suficiente.
- Automatización de tareas.
- DevOps
- SEO
( Y la lista podría continuar, pero con esto englobo casi todo).

**Comment by gala1234** [comment]
Una más al equipoooo!!

**Comment by rcascante** [comment]
Me llamo Rita quiero contribuir
Adalaber-Front End Developer Junior
Conozco estructura y funcionamiento de Metodologías Ágiles
Qué se me da bien:
- Maquetación, usando herramientas tales como CSS Grid y Flexbox
En qué estoy verde y me gustaría aprender:
- Javascript 
- Empezar a conocer Backend y trabajar con otros desarroladores
Qué tardes en montar un landing:
2 días

**Comment by ElenaCerezoSwing** [comment]
Me apunto!!!!!

**Comment by MoniAguado** [comment]
Soy Mónica!

Puedo contribuir. Aunque también me gusta liderar, aún estoy muy verde en este sector.
Soy Adalaber y estoy estudiando front-end (eso sí, las últimas novedades nos las enseña @oneeyedman )

Podría contribuir en:
 - Maquetación, sobre todo si es con Zeplin (amor a primera vista) y usando Grid y Flexbox como mi compañera Rita
- Antes tenía un blog y escribía. Eso fue antes, pero creo que aún estoy fresca para ayudar en contenido. Conozco algo de SEO, pero me encantaría aprender y mejorar.
- Vengo del Social Media, así que puedo colaborar en la difusión.

Estoy más pez en:
- Javascript (estamos trabajando en ello...)

Me gustaría aprender:
- Javascript a tope
- Trabajo en equipo con diseñadores y backends
- Experiencia de usuario
- Más SEO
- Project Management

**Comment by CloudsC** [comment]
+1

**Comment by Jorgeural** [comment]
Me apunto! 

Soy Jorge, Dveloper Junior autodidacta, pero con muchas ganas de aprender.

Tengo experiencia en SQL, .Net, AngularJs.

Deseando poder aportar algo y aprender mucho de esta comunidad ;)

**Comment by ismaelocaramelo** [comment]
Hola !

Gracias por todas esas maravillosas introducciones. 

> En lo que a mi respecta, trabajo como Full-Stack en BME. Me gustaría colaborar como **contributor**. 

> Me encanta el mundo JavaScript e intento mantenerme al día con lo último. Me motiva mucho poder ayudar a gente, seguir aprendiendo y ser parte del open-source. 

> Por último, lo que me "paetece" (@UlisesGascon) hacer es colaborar en la parte front, aunque no me importaría ayudar al back. Diseño y maquetación es algo que todavía tengo pendiente de mejorar :blush:. 

Un Saludo !
Ismael

**Comment by baumannzone** [comment]
Yoooooo! +1 here*

**Comment by Josheriff** [comment]
Yo me tengo que apuntar o estaba preliado?

Jeje

**Comment by Sediug** [comment]
Hay Jose que cosas dices. A ti te pasará como a mí, en cuanto te descuides estás liado jaja

**Comment by UlisesGascon** [comment]
Os he añadido como miembros de la organización. Recordad que teneis que aceptar la invitación pinchando en este [link](https://github.com/OSWeekends). En breve creo un canal de Slack para organizarnos ;-)

**Comment by bytelovers** [comment]
+1 en lo que pueda echar una mano.

Desarrollo front desde hace eones y me ha tocado contribuir y liderar así que para lo que haga falta

**Comment by AnitaMartinez** [comment]
Buenas! 

Me llamo Anita y soy estudiante de front-end en Adalab. 
Podría contribuir con la maquetación, SASS/CSS… Y me gustaría seguir aprendiendo con JS (ahora comenzando con React). 

Encantada de estar aquí! :)

**Comment by david-cm-dev** [comment]
Me apunto

Me llamo David. Soy desarrollador Fullstack.
 React, vuejs, y nodejs. Puedo echar una mano tanto en front como en back.

**Comment by UlisesGascon** [comment]
Hola de nuevo!! No olvideis apuntaros en http://guilds.osweekends.com! :-)
