### ISSUE TITLE
Brainstorming...

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/guilds.osweekends.com#4]
### Ideas...

**Diseño**
-  [ ] Licencias...

**Textos**
- [ ] Licencias

**Haciendo cosas cool/automatizacion?**
- [ ] Usemos [Gulp](https://gulpjs.com/)

**Front**
- [ ]  [Grid CSS](https://developer.mozilla.org/es/docs/Web/CSS/grid)?
- [ ] Usaremos [Polymer](https://www.polymer-project.org/)?
- [ ] [Arquitectura 7 - 1](https://sass-guidelin.es/#the-7-1-pattern) 
- [ ] [Sass](http://sass-lang.com/)...?
- [ ] [Ajax](https://es.wikipedia.org/wiki/AJAX)? 
- [ ] HighCharts, D3...?
- [ ] [Zeplin](https://zeplin.io/)

**Front Vistas**
- [ ] Info de perfiles
- [ ] Info de proyectos
- [ ] Info de Guilds

**Back**

- [ ] [Nodejs](https://es.wikipedia.org/wiki/Node.js)?
- [ ] [API Rest](https://es.wikipedia.org/wiki/Transferencia_de_Estado_Representacional)...?
- [ ] [MongoDB](https://es.wikipedia.org/wiki/MongoDB)
- [ ] Login con [passportjs](http://www.passportjs.org/)

**Traer datos de Github**
- [ ] Api [GraphQL](http://graphql.org/learn/) de github .. usaremos?
- [ ] Meteremos [GoblinDB](http://goblindb.osweekends.com/) para cachear?

**Comment by Jorgeural** [comment]
- Definir si se va a utilizar alguna framework de front, en caso afirmativo,  cual?
- Guía de estilos ?

**Comment by jsmanrique** [comment]
Podría ser interesante ver cómo meter datos de [Perceval](https://github.com/chaoss/grimoirelab-perceval) en GoblinDB
